lint:
  files_exist:
    - .github/workflows/linting_comment.yml
  files_unchanged:
    - .github/workflows/branch.yml
    - .github/workflows/linting.yml
nf_core_version: 4.1.0
repository_type: pipeline
template:
  author: Poma-Soto Franco
  description: a pipeline to process sequencing based spatial transccriptomics data
    from in-situ arrays
  force: false
  is_nfcore: true
  name: panoramaseq
  org: nf-core
  outdir: .
  skip_features: []
  version: 1.0.0dev
