repository_type: pipeline

nf_core_version: 3.2.1

lint: {}

template:
  org: nf-core
  name: panoramaseq
  description: a pipeline to process sequencing based spatial transccriptomics data
    from in-situ arrays
  author: Poma-Soto Franco
  version: 1.0.0dev
  force: true
  outdir: .
  skip_features: []
  is_nfcore: true
