contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #panoramaseq channel"
    url: https://nfcore.slack.com/channels/panoramaseq
    about: Discussion about the nf-core/panoramaseq pipeline
